const map=L.map("map",{zoomControl:false}).setView([-23.1337,-46.3015],16);
L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap"}).addTo(map);
let camadaDelineacao=null,rotaSelecionadaId=null,ruaSelecionada=null,fotosPendentes=[];
const MES_ATUAL=()=>new Date().toISOString().slice(0,7);
const coordenadasDasRotas={"ROTA 1":[[-23.1330,-46.3010],[-23.1340,-46.3020],[-23.1350,-46.3030]],"ROTA 2":[[-23.1320,-46.3015],[-23.1325,-46.3025],[-23.1330,-46.3035]],"ROTA 3":[[-23.1352,-46.3005],[-23.1358,-46.3012],[-23.1365,-46.3020]],"ROTA 4":[[-23.1340,-46.2990],[-23.1345,-46.2980],[-23.1350,-46.2970]],"ROTA 5":[[-23.1310,-46.3000],[-23.1315,-46.2990],[-23.1320,-46.2980]],"ROTA 6":[[-23.1360,-46.3040],[-23.1370,-46.3050],[-23.1380,-46.3060]],"ROTA 7":[[-23.1335,-46.3045],[-23.1340,-46.3055],[-23.1345,-46.3065]],"ROTA 8":[[-23.1310,-46.3050],[-23.1300,-46.3060],[-23.1290,-46.3070]],"ROTA 9":[[-23.1300,-46.3020],[-23.1285,-46.3015],[-23.1270,-46.3010]],"ROTA 10":[[-23.1370,-46.3000],[-23.1385,-46.2995],[-23.1400,-46.2990]],"ROTA 11":[[-23.1320,-46.3080],[-23.1310,-46.3090],[-23.1300,-46.3100]],"ROTA 12":[[-23.1350,-46.3080],[-23.1365,-46.3095],[-23.1380,-46.3110]],"ROTA 13":[[-23.1340,-46.3030],[-23.1325,-46.3035],[-23.1310,-46.3040]],"ROTA 14":[[-23.1380,-46.3020],[-23.1395,-46.3015],[-23.1410,-46.3010]],"ROTA 15":[[-23.1390,-46.3050],[-23.1405,-46.3055],[-23.1420,-46.3060]],"ROTA 16":[[-23.1305,-46.3040],[-23.1290,-46.3045],[-23.1275,-46.3050]],"ROTA 17":[[-23.1345,-46.2975],[-23.1360,-46.2970],[-23.1375,-46.2965]],"ROTA 18":[[-23.1325,-46.3115],[-23.1335,-46.3125],[-23.1345,-46.3135]],"ROTA 19":[[-23.1285,-46.3025],[-23.1270,-46.3020],[-23.1255,-46.3015]],"ROTA 20":[[-23.1375,-46.3085],[-23.1390,-46.3090],[-23.1405,-46.3095]]};
function atualizarStatus(){const e=document.getElementById("status-offline");if(!navigator.onLine){e.textContent="● OFFLINE — DADOS LOCAIS";e.className="status-offline-mode"}else{e.textContent="● ONLINE";e.className="status-online"}}
window.addEventListener("online",atualizarStatus);window.addEventListener("offline",atualizarStatus);
function abrirMapa(){document.getElementById("tela-identidade").style.transform="translateY(-100%)";atualizarStatus();map.locate({setView:true,watch:true,maxZoom:18});renderizarMenuRotas();setTimeout(()=>lucide.createIcons(),50)}
map.on("locationfound",e=>{if(window.userMarker)window.userMarker.setLatLng(e.latlng);else window.userMarker=L.circleMarker(e.latlng,{radius:8,color:"#fff",fillColor:"#007bff",fillOpacity:1,weight:3}).addTo(map)});
function abrirMenuRotas(){document.getElementById("menu-rotas").classList.add("aberto");document.getElementById("menu-overlay").classList.add("aberto")}
function fecharMenuRotas(){document.getElementById("menu-rotas").classList.remove("aberto");document.getElementById("menu-overlay").classList.remove("aberto")}
function renderizarMenuRotas(){const c=document.getElementById("lista-rotas-menu");c.innerHTML="";Object.keys(bancoDeRotas).forEach(id=>{const b=document.createElement("button");b.className="rota-menu-item"+(id===rotaSelecionadaId?" ativa":"");b.innerHTML='<span class="numero" style="background:'+bancoDeRotas[id].cor+'">'+id.replace("ROTA ","")+'</span><span>'+id+'<br><small style="opacity:.5">'+bancoDeRotas[id].ruas.length+' endereços</small></span>';b.onclick=()=>{selecionarRota(id);fecharMenuRotas()};c.appendChild(b)});lucide.createIcons()}
async function selecionarRota(id){rotaSelecionadaId=id;ruaSelecionada=null;fotosPendentes=[];const rota=bancoDeRotas[id],pts=coordenadasDasRotas[id];if(camadaDelineacao)map.removeLayer(camadaDelineacao);if(pts){camadaDelineacao=L.polyline(pts,{color:rota.cor,weight:12,opacity:.8}).addTo(map);map.fitBounds(camadaDelineacao.getBounds(),{padding:[30,120]})}
document.getElementById("rua-nome").textContent=id;document.getElementById("rua-nome").style.color=rota.cor;document.getElementById("rota-badge").textContent=id+" • "+rota.ruas.length+" ENDEREÇOS";document.getElementById("rota-contador").textContent="Mês atual: "+MES_ATUAL();document.getElementById("busca-rua").value="";document.getElementById("gaveta").classList.add("aberta");document.getElementById("painel-rua").classList.add("oculto");renderizarMenuRotas();await renderizarListaRuas()}
async function renderizarListaRuas(filtro=""){if(!rotaSelecionadaId)return;const rota=bancoDeRotas[rotaSelecionadaId],registros=await obterRegistrosDaRota(rotaSelecionadaId,MES_ATUAL()),salvos=new Set(registros.map(x=>x.rua)),termo=filtro.trim().toLowerCase(),lista=rota.ruas.filter(r=>r.toLowerCase().includes(termo)),c=document.getElementById("lista-ruas");c.innerHTML="";lista.forEach((rua,i)=>{const item=document.createElement("div");item.className="item-rua"+(rua===ruaSelecionada?" selecionada":"");item.innerHTML='<span class="check">'+(salvos.has(rua)?"✔️":"○")+'</span><button>'+String(i+1)+". "+rua+'</button><button class="pin" title="Abrir navegação"><i data-lucide="map-pin"></i></button>';item.querySelector("button").onclick=()=>selecionarRua(rua);item.querySelector(".pin").onclick=()=>abrirNavegacao(rua);c.appendChild(item)});lucide.createIcons()}
function filtrarRuas(v){renderizarListaRuas(v)}
function atualizarContador(){const e=document.getElementById("obs");document.getElementById("contador-obs").textContent=e.value.length}
async function selecionarRua(rua){ruaSelecionada=rua;fotosPendentes=[];document.getElementById("painel-rua").classList.remove("oculto");document.getElementById("painel-rua-nome").textContent=rua;document.getElementById("rua-nome").textContent=rua;document.getElementById("status-salvo").textContent="";document.getElementById("foto-status").textContent="";document.getElementById("cam").value="";const id=rotaSelecionadaId+"::"+MES_ATUAL()+"::"+rua;const r=await obterRegistroOffline(id);document.getElementById("leitura").value=r?.leitura||"";document.getElementById("obs").value=r?.obs||"";atualizarContador();await renderizarGaleria(id);await renderizarListaRuas(document.getElementById("busca-rua").value)}
async function comprimirFoto(file){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const max=1600;let w=img.naturalWidth,h=img.naturalHeight;if(w>max||h>max){const escala=Math.min(max/w,max/h);w=Math.round(w*escala);h=Math.round(h*escala)}const canvas=document.createElement("canvas");canvas.width=w;canvas.height=h;canvas.getContext("2d").drawImage(img,0,0,w,h);canvas.toBlob(blob=>{URL.revokeObjectURL(url);blob?resolve(blob):reject(new Error("Falha ao preparar foto"))},"image/jpeg",.82)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error("Imagem inválida"))};img.src=url})}
async function selecionarFoto(e){const file=e.target.files?.[0];if(!file||!ruaSelecionada||!rotaSelecionadaId)return;const mes=MES_ATUAL(),registroId=rotaSelecionadaId+"::"+mes+"::"+ruaSelecionada,existentes=await obterFotosDoMes(mes);if(existentes.length>=50){document.getElementById("foto-status").textContent="⚠️ Limite de 50 fotos deste mês atingido.";e.target.value="";return}try{document.getElementById("foto-status").textContent="⏳ Salvando foto...";const blob=await comprimirFoto(file);await salvarFotoOffline({id:crypto.randomUUID(),registroId,rotaId:rotaSelecionadaId,rua:ruaSelecionada,mes,blob,criadaEm:new Date().toISOString()});document.getElementById("foto-status").textContent="✅ Foto salva neste endereço.";await renderizarGaleria(registroId)}catch(err){document.getElementById("foto-status").textContent="❌ Não foi possível salvar a foto.";console.error(err)}finally{e.target.value=""}}
async function renderizarGaleria(registroId){const c=document.getElementById("galeria-fotos");c.innerHTML="";const fotos=await obterFotosDoRegistro(registroId),mesFotos=await obterFotosDoMes(MES_ATUAL());document.getElementById("contador-fotos").textContent="📷 "+mesFotos.length+"/50 fotos usadas em "+MES_ATUAL();for(const foto of fotos){const item=document.createElement("div");item.className="foto-item";const url=URL.createObjectURL(foto.blob);item.innerHTML='<img src="'+url+'"><button title="Apagar foto"><i data-lucide="trash-2"></i></button>';item.querySelector("button").onclick=async()=>{if(confirm("Apagar esta foto?")){await apagarFotoOffline(foto.id);URL.revokeObjectURL(url);await renderizarGaleria(registroId)}};c.appendChild(item)}lucide.createIcons()}
function abrirNavegacao(rua){const q=encodeURIComponent(rua+", Bom Jesus dos Perdões, SP, Brasil");window.open("https://www.google.com/maps/search/?api=1&query="+q,"_blank","noopener")}
function navegarParaRua(){if(ruaSelecionada)abrirNavegacao(ruaSelecionada)}
async function salvar(){if(!rotaSelecionadaId||!ruaSelecionada){alert("Selecione uma rua primeiro.");return}const mes=MES_ATUAL(),id=rotaSelecionadaId+"::"+mes+"::"+ruaSelecionada,obs=document.getElementById("obs").value.slice(0,100);const registro={id,rotaId:rotaSelecionadaId,rua:ruaSelecionada,mes,leitura:document.getElementById("leitura").value,obs,atualizadoEm:new Date().toISOString()};try{await salvarRegistroOffline(registro);document.getElementById("status-salvo").textContent="✅ Leitura salva neste aparelho.";await renderizarGaleria(id);await renderizarListaRuas(document.getElementById("busca-rua").value)}catch(e){document.getElementById("status-salvo").textContent="❌ Não foi possível salvar localmente.";console.error(e)}}
function fecharGaveta(){document.getElementById("gaveta").classList.remove("aberta")}
atualizarStatus();